### ISSUE TITLE
Download as Zip Supplies Empty Zip Folder

### ISSUE THREAD

**Issue by Planet-Earth** [oferei/sublime-unity-completions#11]
Stated in title: When downloading as Zip, the Zip folder comes empty.

**Comment by Pendrokar** [comment]
Unable to reproduce and sounds more like a GitHub issue rather than the repository's. Also oferei might recommend the light version of this package.
https://github.com/oferei/sublime-unity-completions-light

**Comment by oferei** [comment]
yup, same here. successfully downloaded a 47.7 MB zip file. sounds like a GitHub issue.

I usually recommend the light version of the package when encountering problems when using Package Control, or if you don't want a 5-sec delay whenever you open Sublime. but you're welcome to try it somehow works around GitHub's issues!
