### ISSUE TITLE
Completes appearing before the keyword

### ISSUE THREAD

**Issue by peteski** [oferei/sublime-unity-completions#12]
Hi there, 

I'm loving these completions, but I keep running into this issue and maybe it's just something to do with I'm using them. 

The problem I am having is this - 
I start typing some thing (like instantiate) and it has picked out the right completion for me, ace!
<img width="541" alt="screen shot 2015-07-08 at 9 20 03 pm" src="https://cloud.githubusercontent.com/assets/3522412/8569105/5b39abec-25b7-11e5-89b4-185fbd09c2ea.png">

But when I hit enter it will always add the class in front, like "Object" here.
<img width="871" alt="screen shot 2015-07-08 at 9 20 15 pm" src="https://cloud.githubusercontent.com/assets/3522412/8569117/697fbb9c-25b7-11e5-9692-d0219617f82c.png">
So i have to go back and delete the "Object" part. 

Here's another example with localEulerAngles. 
<img width="661" alt="screen shot 2015-07-08 at 9 27 23 pm" src="https://cloud.githubusercontent.com/assets/3522412/8569181/32d20798-25b8-11e5-99ef-d8165183faba.png">

<img width="482" alt="screen shot 2015-07-08 at 9 27 31 pm" src="https://cloud.githubusercontent.com/assets/3522412/8569182/35d19148-25b8-11e5-8458-288e185974d9.png">

Any ideas on how I could get it to stop this? Apart from that it really is working great...

Thanks,
Pete

**Comment by oferei** [comment]
hey Pete,
first of all, you are most welcome! I'm glad that you can do Unity with Sublime.  :)
about the behavior you described, alas, it is a known issue that cannot be fixed. I explained it <a href="https://github.com/oferei/sublime-unity-completions#limitations">in the documentation</a>. unfortunately this is a limitation of Sublime Text's auto-completions.

the only way to build a better plug-in would be to incorporate a full language analyzer to intelligently infer the context (the variable types). to continue your example, the plug-in does not "know" that you are completing player.transform - it has no idea of the context.

keep on rockin'
Ofer Reichman

**Comment by oferei** [comment]
duplicate of #9

**Comment by peteski** [comment]
Ahhh bummer! Well it's still super handy. 
Thanks,
Pete
