### ISSUE TITLE
class names are being added

### ISSUE THREAD

**Issue by damonbla** [oferei/sublime-unity-completions#15]
Hello! Thank you for the awesome package here. It has made my Unity C# programming far easier. Without this for Sublime Text I'd probably be stuck in Mono, and nobody wants that!

I've got just one thing: when I autocomplete something, it adds the class name and not just the variable. For example, if I start typing:

myObject.tran

It pops up with all the correct code completion options - all the classes in Unity with "transform" that exist. When I hit enter or tab to do the completion however, it ends up like this:

myObject.GameObject.transform or myObject.Collision.transform or whatever class I happen to hit enter or tab to autocomplete on, instead of just this:

myGameObject.transform

Is there any way to stop it from adding the class to the code completions?

**Comment by oferei** [comment]
hey, first of all, thanks. :)
the short answer is: no. not easily at least. it's a [limitation](https://github.com/oferei/sublime-unity-completions/#limitations) of sublime's auto-complete feature.

I don't know sublime text plugins well enough, but I'm guessing there's a way for a plugin to analyze code and figure out variables, their types and their members and methods, but, alas, it's beyond the scope of this project.

**Comment by damonbla** [comment]
Damn, well thank you. Also, sorry about this one - I should have read through your readme a bit more closely!

I actually posted nearly this same thing to the Sublime Text forums yesterday and someone there said that it was probably due to how this plugin worked. It sounds like it's actually just how Sublime Text works. Maybe if I get a chance someday I'll look through the code myself. Thanks again!
