### ISSUE TITLE
Possible Fix to @Limitations listed in Readme

### ISSUE THREAD

**Issue by Penguin98kStudio** [oferei/sublime-unity-completions#17]
Anaconda package uses this to allow . to be used in autocompletion. If you are familiar with sublime syntax ways you could most likely do an equivalent for c#.
This should easily fix the issue

I will try to edit this post after I test it myself to confirm the solution
```
{
    "auto_complete_triggers": [{"selector": "source.python - string - comment
    - constant.numeric", "characters": "."}]
}
```

**Comment by oferei** [comment]
I don't know Anaconda, but I'm guessing this small snippet relies on much more code that is included the their package.
I also believe that Sublime Text lacks the context needed for auto-complete. It doesn't understand C# code nor Unity projects.

**Comment by oferei** [comment]
But I'd be happy to find out that I'm wrong!

**Comment by Penguin98kStudio** [comment]
I will try to look in more depth for the solution into this issue, it wasn't as simple I initially thought.
No hopes though :'(

Will reopen the issue if I get results

**Comment by oferei** [comment]
Cheers, mate!
